//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LivrariaModel", "ItemVendaVenda", "ItemVenda", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Model.ItemVenda), "Venda", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Model.Venda))]
[assembly: EdmRelationshipAttribute("LivrariaModel", "ProdutoItemVenda", "Produto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Model.Produto), "ItemVenda", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Model.ItemVenda))]
[assembly: EdmRelationshipAttribute("LivrariaModel", "PessoaVenda", "Pessoa", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Model.Pessoa), "Venda", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Model.Venda))]
[assembly: EdmRelationshipAttribute("LivrariaModel", "TelefonePessoa", "Telefone", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Model.Telefone), "Pessoa", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Model.Pessoa))]
[assembly: EdmRelationshipAttribute("LivrariaModel", "EnderecoPessoa", "Endereco", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Model.Endereco), "Pessoa", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Model.Pessoa))]

#endregion

namespace Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LivrariaModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LivrariaModelContainer object using the connection string found in the 'LivrariaModelContainer' section of the application configuration file.
        /// </summary>
        public LivrariaModelContainer() : base("name=LivrariaModelContainer", "LivrariaModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LivrariaModelContainer object.
        /// </summary>
        public LivrariaModelContainer(string connectionString) : base(connectionString, "LivrariaModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LivrariaModelContainer object.
        /// </summary>
        public LivrariaModelContainer(EntityConnection connection) : base(connection, "LivrariaModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Venda> Venda
        {
            get
            {
                if ((_Venda == null))
                {
                    _Venda = base.CreateObjectSet<Venda>("Venda");
                }
                return _Venda;
            }
        }
        private ObjectSet<Venda> _Venda;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ItemVenda> ItemVenda
        {
            get
            {
                if ((_ItemVenda == null))
                {
                    _ItemVenda = base.CreateObjectSet<ItemVenda>("ItemVenda");
                }
                return _ItemVenda;
            }
        }
        private ObjectSet<ItemVenda> _ItemVenda;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Produto> Produto
        {
            get
            {
                if ((_Produto == null))
                {
                    _Produto = base.CreateObjectSet<Produto>("Produto");
                }
                return _Produto;
            }
        }
        private ObjectSet<Produto> _Produto;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pessoa> Pessoa
        {
            get
            {
                if ((_Pessoa == null))
                {
                    _Pessoa = base.CreateObjectSet<Pessoa>("Pessoa");
                }
                return _Pessoa;
            }
        }
        private ObjectSet<Pessoa> _Pessoa;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Telefone> Telefone
        {
            get
            {
                if ((_Telefone == null))
                {
                    _Telefone = base.CreateObjectSet<Telefone>("Telefone");
                }
                return _Telefone;
            }
        }
        private ObjectSet<Telefone> _Telefone;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Endereco> Endereco
        {
            get
            {
                if ((_Endereco == null))
                {
                    _Endereco = base.CreateObjectSet<Endereco>("Endereco");
                }
                return _Endereco;
            }
        }
        private ObjectSet<Endereco> _Endereco;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Venda EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVenda(Venda venda)
        {
            base.AddObject("Venda", venda);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ItemVenda EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItemVenda(ItemVenda itemVenda)
        {
            base.AddObject("ItemVenda", itemVenda);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Produto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProduto(Produto produto)
        {
            base.AddObject("Produto", produto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pessoa EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPessoa(Pessoa pessoa)
        {
            base.AddObject("Pessoa", pessoa);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Telefone EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTelefone(Telefone telefone)
        {
            base.AddObject("Telefone", telefone);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Endereco EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEndereco(Endereco endereco)
        {
            base.AddObject("Endereco", endereco);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LivrariaModel", Name="Endereco")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Endereco : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Endereco object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="logradouro">Initial value of the Logradouro property.</param>
        /// <param name="uF">Initial value of the UF property.</param>
        /// <param name="cidade">Initial value of the Cidade property.</param>
        /// <param name="bairro">Initial value of the Bairro property.</param>
        /// <param name="complemento">Initial value of the Complemento property.</param>
        public static Endereco CreateEndereco(global::System.Int32 id, global::System.String logradouro, global::System.String uF, global::System.String cidade, global::System.String bairro, global::System.String complemento)
        {
            Endereco endereco = new Endereco();
            endereco.Id = id;
            endereco.Logradouro = logradouro;
            endereco.UF = uF;
            endereco.Cidade = cidade;
            endereco.Bairro = bairro;
            endereco.Complemento = complemento;
            return endereco;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Logradouro
        {
            get
            {
                return _Logradouro;
            }
            set
            {
                OnLogradouroChanging(value);
                ReportPropertyChanging("Logradouro");
                _Logradouro = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Logradouro");
                OnLogradouroChanged();
            }
        }
        private global::System.String _Logradouro;
        partial void OnLogradouroChanging(global::System.String value);
        partial void OnLogradouroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UF
        {
            get
            {
                return _UF;
            }
            set
            {
                OnUFChanging(value);
                ReportPropertyChanging("UF");
                _UF = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UF");
                OnUFChanged();
            }
        }
        private global::System.String _UF;
        partial void OnUFChanging(global::System.String value);
        partial void OnUFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cidade
        {
            get
            {
                return _Cidade;
            }
            set
            {
                OnCidadeChanging(value);
                ReportPropertyChanging("Cidade");
                _Cidade = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Cidade");
                OnCidadeChanged();
            }
        }
        private global::System.String _Cidade;
        partial void OnCidadeChanging(global::System.String value);
        partial void OnCidadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Bairro
        {
            get
            {
                return _Bairro;
            }
            set
            {
                OnBairroChanging(value);
                ReportPropertyChanging("Bairro");
                _Bairro = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Bairro");
                OnBairroChanged();
            }
        }
        private global::System.String _Bairro;
        partial void OnBairroChanging(global::System.String value);
        partial void OnBairroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Complemento
        {
            get
            {
                return _Complemento;
            }
            set
            {
                OnComplementoChanging(value);
                ReportPropertyChanging("Complemento");
                _Complemento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Complemento");
                OnComplementoChanged();
            }
        }
        private global::System.String _Complemento;
        partial void OnComplementoChanging(global::System.String value);
        partial void OnComplementoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LivrariaModel", "EnderecoPessoa", "Pessoa")]
        public Pessoa Pessoa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pessoa>("LivrariaModel.EnderecoPessoa", "Pessoa").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pessoa>("LivrariaModel.EnderecoPessoa", "Pessoa").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Pessoa> PessoaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pessoa>("LivrariaModel.EnderecoPessoa", "Pessoa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Pessoa>("LivrariaModel.EnderecoPessoa", "Pessoa", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LivrariaModel", Name="Fisica")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Fisica : Pessoa
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Fisica object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="cPF">Initial value of the CPF property.</param>
        /// <param name="rG">Initial value of the RG property.</param>
        /// <param name="dataNascimento">Initial value of the DataNascimento property.</param>
        public static Fisica CreateFisica(global::System.Int32 id, global::System.String nome, global::System.String cPF, global::System.String rG, global::System.String dataNascimento)
        {
            Fisica fisica = new Fisica();
            fisica.Id = id;
            fisica.Nome = nome;
            fisica.CPF = cPF;
            fisica.RG = rG;
            fisica.DataNascimento = dataNascimento;
            return fisica;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CPF
        {
            get
            {
                return _CPF;
            }
            set
            {
                OnCPFChanging(value);
                ReportPropertyChanging("CPF");
                _CPF = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CPF");
                OnCPFChanged();
            }
        }
        private global::System.String _CPF;
        partial void OnCPFChanging(global::System.String value);
        partial void OnCPFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RG
        {
            get
            {
                return _RG;
            }
            set
            {
                OnRGChanging(value);
                ReportPropertyChanging("RG");
                _RG = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RG");
                OnRGChanged();
            }
        }
        private global::System.String _RG;
        partial void OnRGChanging(global::System.String value);
        partial void OnRGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DataNascimento
        {
            get
            {
                return _DataNascimento;
            }
            set
            {
                OnDataNascimentoChanging(value);
                ReportPropertyChanging("DataNascimento");
                _DataNascimento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DataNascimento");
                OnDataNascimentoChanged();
            }
        }
        private global::System.String _DataNascimento;
        partial void OnDataNascimentoChanging(global::System.String value);
        partial void OnDataNascimentoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LivrariaModel", Name="ItemVenda")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ItemVenda : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ItemVenda object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="quantidade">Initial value of the Quantidade property.</param>
        public static ItemVenda CreateItemVenda(global::System.Int32 id, global::System.String quantidade)
        {
            ItemVenda itemVenda = new ItemVenda();
            itemVenda.Id = id;
            itemVenda.Quantidade = quantidade;
            return itemVenda;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Quantidade
        {
            get
            {
                return _Quantidade;
            }
            set
            {
                OnQuantidadeChanging(value);
                ReportPropertyChanging("Quantidade");
                _Quantidade = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Quantidade");
                OnQuantidadeChanged();
            }
        }
        private global::System.String _Quantidade;
        partial void OnQuantidadeChanging(global::System.String value);
        partial void OnQuantidadeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LivrariaModel", "ItemVendaVenda", "Venda")]
        public Venda Venda
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Venda>("LivrariaModel.ItemVendaVenda", "Venda").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Venda>("LivrariaModel.ItemVendaVenda", "Venda").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Venda> VendaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Venda>("LivrariaModel.ItemVendaVenda", "Venda");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Venda>("LivrariaModel.ItemVendaVenda", "Venda", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LivrariaModel", "ProdutoItemVenda", "Produto")]
        public Produto Produto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produto>("LivrariaModel.ProdutoItemVenda", "Produto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produto>("LivrariaModel.ProdutoItemVenda", "Produto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Produto> ProdutoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produto>("LivrariaModel.ProdutoItemVenda", "Produto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Produto>("LivrariaModel.ProdutoItemVenda", "Produto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LivrariaModel", Name="Juridica")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Juridica : Pessoa
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Juridica object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="razaoSocial">Initial value of the RazaoSocial property.</param>
        /// <param name="cNPJ">Initial value of the CNPJ property.</param>
        /// <param name="inscricaoEstadual">Initial value of the InscricaoEstadual property.</param>
        /// <param name="inscricaoMunicipal">Initial value of the InscricaoMunicipal property.</param>
        /// <param name="dataFundacao">Initial value of the DataFundacao property.</param>
        public static Juridica CreateJuridica(global::System.Int32 id, global::System.String razaoSocial, global::System.String cNPJ, global::System.String inscricaoEstadual, global::System.String inscricaoMunicipal, global::System.DateTime dataFundacao)
        {
            Juridica juridica = new Juridica();
            juridica.Id = id;
            juridica.RazaoSocial = razaoSocial;
            juridica.CNPJ = cNPJ;
            juridica.InscricaoEstadual = inscricaoEstadual;
            juridica.InscricaoMunicipal = inscricaoMunicipal;
            juridica.DataFundacao = dataFundacao;
            return juridica;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RazaoSocial
        {
            get
            {
                return _RazaoSocial;
            }
            set
            {
                OnRazaoSocialChanging(value);
                ReportPropertyChanging("RazaoSocial");
                _RazaoSocial = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RazaoSocial");
                OnRazaoSocialChanged();
            }
        }
        private global::System.String _RazaoSocial;
        partial void OnRazaoSocialChanging(global::System.String value);
        partial void OnRazaoSocialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CNPJ
        {
            get
            {
                return _CNPJ;
            }
            set
            {
                OnCNPJChanging(value);
                ReportPropertyChanging("CNPJ");
                _CNPJ = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CNPJ");
                OnCNPJChanged();
            }
        }
        private global::System.String _CNPJ;
        partial void OnCNPJChanging(global::System.String value);
        partial void OnCNPJChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String InscricaoEstadual
        {
            get
            {
                return _InscricaoEstadual;
            }
            set
            {
                OnInscricaoEstadualChanging(value);
                ReportPropertyChanging("InscricaoEstadual");
                _InscricaoEstadual = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("InscricaoEstadual");
                OnInscricaoEstadualChanged();
            }
        }
        private global::System.String _InscricaoEstadual;
        partial void OnInscricaoEstadualChanging(global::System.String value);
        partial void OnInscricaoEstadualChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String InscricaoMunicipal
        {
            get
            {
                return _InscricaoMunicipal;
            }
            set
            {
                OnInscricaoMunicipalChanging(value);
                ReportPropertyChanging("InscricaoMunicipal");
                _InscricaoMunicipal = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("InscricaoMunicipal");
                OnInscricaoMunicipalChanged();
            }
        }
        private global::System.String _InscricaoMunicipal;
        partial void OnInscricaoMunicipalChanging(global::System.String value);
        partial void OnInscricaoMunicipalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataFundacao
        {
            get
            {
                return _DataFundacao;
            }
            set
            {
                OnDataFundacaoChanging(value);
                ReportPropertyChanging("DataFundacao");
                _DataFundacao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataFundacao");
                OnDataFundacaoChanged();
            }
        }
        private global::System.DateTime _DataFundacao;
        partial void OnDataFundacaoChanging(global::System.DateTime value);
        partial void OnDataFundacaoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LivrariaModel", Name="Pessoa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(Juridica))]
    [KnownTypeAttribute(typeof(Fisica))]
    public partial class Pessoa : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pessoa object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Pessoa CreatePessoa(global::System.Int32 id)
        {
            Pessoa pessoa = new Pessoa();
            pessoa.Id = id;
            return pessoa;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Observacao
        {
            get
            {
                return _Observacao;
            }
            set
            {
                OnObservacaoChanging(value);
                ReportPropertyChanging("Observacao");
                _Observacao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Observacao");
                OnObservacaoChanged();
            }
        }
        private global::System.String _Observacao;
        partial void OnObservacaoChanging(global::System.String value);
        partial void OnObservacaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LivrariaModel", "PessoaVenda", "Venda")]
        public EntityCollection<Venda> Venda
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Venda>("LivrariaModel.PessoaVenda", "Venda");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Venda>("LivrariaModel.PessoaVenda", "Venda", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LivrariaModel", "TelefonePessoa", "Telefone")]
        public EntityCollection<Telefone> Telefone
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Telefone>("LivrariaModel.TelefonePessoa", "Telefone");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Telefone>("LivrariaModel.TelefonePessoa", "Telefone", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LivrariaModel", "EnderecoPessoa", "Endereco")]
        public EntityCollection<Endereco> Endereco
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Endereco>("LivrariaModel.EnderecoPessoa", "Endereco");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Endereco>("LivrariaModel.EnderecoPessoa", "Endereco", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LivrariaModel", Name="Produto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Produto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Produto object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        /// <param name="valor">Initial value of the Valor property.</param>
        public static Produto CreateProduto(global::System.Int32 id, global::System.String nome, global::System.String descricao, global::System.Double valor)
        {
            Produto produto = new Produto();
            produto.Id = id;
            produto.Nome = nome;
            produto.Descricao = descricao;
            produto.Valor = valor;
            return produto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Valor
        {
            get
            {
                return _Valor;
            }
            set
            {
                OnValorChanging(value);
                ReportPropertyChanging("Valor");
                _Valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Valor");
                OnValorChanged();
            }
        }
        private global::System.Double _Valor;
        partial void OnValorChanging(global::System.Double value);
        partial void OnValorChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LivrariaModel", Name="Telefone")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Telefone : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Telefone object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="numero">Initial value of the Numero property.</param>
        public static Telefone CreateTelefone(global::System.Int32 id, global::System.String numero)
        {
            Telefone telefone = new Telefone();
            telefone.Id = id;
            telefone.Numero = numero;
            return telefone;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DDD
        {
            get
            {
                return _DDD;
            }
            set
            {
                OnDDDChanging(value);
                ReportPropertyChanging("DDD");
                _DDD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DDD");
                OnDDDChanged();
            }
        }
        private global::System.String _DDD;
        partial void OnDDDChanging(global::System.String value);
        partial void OnDDDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Numero
        {
            get
            {
                return _Numero;
            }
            set
            {
                OnNumeroChanging(value);
                ReportPropertyChanging("Numero");
                _Numero = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Numero");
                OnNumeroChanged();
            }
        }
        private global::System.String _Numero;
        partial void OnNumeroChanging(global::System.String value);
        partial void OnNumeroChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LivrariaModel", "TelefonePessoa", "Pessoa")]
        public Pessoa Pessoa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pessoa>("LivrariaModel.TelefonePessoa", "Pessoa").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pessoa>("LivrariaModel.TelefonePessoa", "Pessoa").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Pessoa> PessoaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pessoa>("LivrariaModel.TelefonePessoa", "Pessoa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Pessoa>("LivrariaModel.TelefonePessoa", "Pessoa", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LivrariaModel", Name="Venda")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Venda : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Venda object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="dataVenda">Initial value of the DataVenda property.</param>
        public static Venda CreateVenda(global::System.Int32 id, global::System.DateTime dataVenda)
        {
            Venda venda = new Venda();
            venda.Id = id;
            venda.DataVenda = dataVenda;
            return venda;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataVenda
        {
            get
            {
                return _DataVenda;
            }
            set
            {
                OnDataVendaChanging(value);
                ReportPropertyChanging("DataVenda");
                _DataVenda = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataVenda");
                OnDataVendaChanged();
            }
        }
        private global::System.DateTime _DataVenda;
        partial void OnDataVendaChanging(global::System.DateTime value);
        partial void OnDataVendaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LivrariaModel", "ItemVendaVenda", "ItemVenda")]
        public EntityCollection<ItemVenda> ItemVenda
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ItemVenda>("LivrariaModel.ItemVendaVenda", "ItemVenda");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ItemVenda>("LivrariaModel.ItemVendaVenda", "ItemVenda", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LivrariaModel", "PessoaVenda", "Pessoa")]
        public Pessoa Pessoa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pessoa>("LivrariaModel.PessoaVenda", "Pessoa").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pessoa>("LivrariaModel.PessoaVenda", "Pessoa").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Pessoa> PessoaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pessoa>("LivrariaModel.PessoaVenda", "Pessoa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Pessoa>("LivrariaModel.PessoaVenda", "Pessoa", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
